language: ruby
rvm:
  - 2.1.8
  - 2.2.2
  - 2.3.0
  - 2.4.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile-4-2
before_script: bundle install
script:
 - bundle exec rspec spec
 - bundle exec rubocop
matrix:
  allow_failures:
    - rvm: 2.1.8
